name: Daily Conversion

on:
  schedule:
    - cron: '0 16 * * *'  # Every minute for testing; change to '0 16 * * *' for 00:00 WITA (16:00 UTC)
  push:
    branches:
      - main  # Sesuaikan dengan branch utama kamu
    paths:
      - 'host/*.txt'  # Trigger saat file .txt di host/ diupdate
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual


jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run kembar.py
        run: python sumber/kembar.py

      - name: Run convert-host.py
        run: python sumber/convert-host.py

      - name: Run convert.py
        run: python sumber/convert.py

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.AC_AMAN }}"
          git config --global user.email "${{ secrets.AC_AJA }}"
          git add host/*.yaml || echo "No .yaml files to add"
          git commit -m "Daily conversion of .txt to .yaml" || echo "No changes to commit"
          git push || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
