name: Daily Conversion

on:
  schedule:
    - cron: '0 16 * * *'  # Every minute for testing; change to '0 16 * * *' for 00:00 WITA (16:00 UTC)
  push:
    branches:
      - main
    paths:
      - 'host/*.txt'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Ganti dengan versi Python lokal kamu

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: List directory contents
        run: ls -R

      - name: Ensure script permissions
        run: chmod +x sumber/*.py

      - name: Run kembar.py
        run: python3 sumber/kembar.py || { echo 'kembar.py failed'; exit 1; }

      - name: Run convert-host.py
        run: python3 sumber/convert-host.py || { echo 'convert-host.py failed'; exit 1; }

      - name: Run convert.py
        run: python3 sumber/convert.py || { echo 'convert.py failed'; exit 1; }

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ secrets.AC_AMAN }}"
          git config --global user.email "${{ secrets.AC_AJA }}"
          git add host/* || echo "No files to add"
          git commit -m "Daily conversion" || echo "No changes to commit"
          git push || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}